service:
    name: ixt-protect

plugins:
    - serverless-dotenv-plugin
    - serverless-offline
    - serverless-offline-sns
    - serverless-sns-filter
    - serverless-plugin-tracing
    - serverless-pseudo-parameters

provider:
    name: aws
    apiName: ixt-protect
    region: us-east-1
    memorySize: 512
    stage: dev
    runtime: nodejs8.10
    timeout: 25
    versionFunctions: false
    vpc:
        securityGroupIds: ${env:VPC_SECURITY_GROUP_IDS}
        subnetIds: ${env:VPC_SUBNET_IDS}
    environment:
        MYSQL_HOST: ${env:MYSQL_HOST, ''}
        MYSQL_PORT: ${env:MYSQL_PORT, ''}
        MYSQL_USER: ${env:MYSQL_USER, ''}
        MYSQL_PASSWORD: ${env:MYSQL_PASSWORD, ''}
        MYSQL_DATABASE: ${env:MYSQL_DATABASE, ''}
        GATEWAYAPI_URL: ${env:GATEWAYAPI_URL, 'http://localhost:8001'}
        GATEWAYAPI_MOCK_ENABLED: ${env:GATEWAYAPI_MOCK_ENABLED, 'true'}
package:
    individually: false

functions:
    ping:
        handler: src/api/ping.handler
        description: Ping handler
        events:
            - http:
                  path: ping
                  method: get

    saveSignUp:
        handler: src/api/saveSignUp.handler
        description: Save a sign up
        events:
            - http:
                  path: sign-ups
                  method: post

custom:

    serverless-offline:
        port: 3001

    pseudoParameters:
        allowReferences: true