service:
    name: ixt-protect

plugins:
    - serverless-dotenv-plugin
    - serverless-offline
    - serverless-offline-sns
    - serverless-sns-filter
    - serverless-plugin-tracing

provider:
    name: aws
    apiName: ixt-protect
    region: us-east-1
    memorySize: 512
    stage: dev
    runtime: nodejs8.10
    timeout: 25
    versionFunctions: false
    environment:
        MYSQL_HOST: ${env:MYSQL_HOST, ''}
        MYSQL_PORT: ${env:MYSQL_PORT, ''}
        MYSQL_USER: ${env:MYSQL_USER, ''}
        MYSQL_PASSWORD: ${env:MYSQL_PASSWORD, ''}
        MYSQL_DATABASE: ${env:MYSQL_DATABASE, ''}
package:
    individually: true

functions:
    ping:
        handler: src/api/ping.handler
        events:
            - http:
                  path: ping
                  method: get

    signUp:
        handler: src/api/sign-up.handler
        events:
            - http:
                  path: sign-ups
                  method: post

    signIn:
        handler: src/api/sign-in.handler
        events:
            - http:
                  path: sign-ins
                  method: post

    activateMember:
        handler: src/api/activate-member.handler
        events:
            - http:
                  path: activations
                  method: get

    deleteMember:
        handler: src/api/delete-member.handler
        events:
            - http:
                  path: members
                  method: delete
                  cors: true

    updateMember:
        handler: src/api/update-member.handler
        events:
            - http:
                  path: members
                  method: put
                  cors: true

    getMember:
        handler: src/api/get-member.handler
        events:
            - http:
                  path: members
                  method: get
                  cors: true

    passwordReminder:
        handler: src/api/password-reminder.handler
        events:
            - http:
                  path: password-reminders
                  method: post
                  cors: true

    updatePassword:
        handler: src/api/update-password.handler
        events:
            - http:
                  path: passwords
                  method: put
                  cors: true

    signOut:
        handler: src/api/sign-out.handler
        events:
            - http:
                  path: sessions
                  method: delete
                  cors: true

custom:

    serverless-offline:
        port: 3001

    pseudoParameters:
        allowReferences: true