service:
    name: ixt-protect

plugins:
    - serverless-dotenv-plugin
    - serverless-offline
    - serverless-offline-sns
    - serverless-sns-filter
    - serverless-plugin-tracing

provider:
    name: aws
    apiName: ixt-protect
    region: us-east-1
    memorySize: 512
    stage: dev
    runtime: nodejs8.10
    timeout: 25
    versionFunctions: false
    vpc:
        securityGroupIds: ${env:VPC_SECURITY_GROUP_IDS}
        subnetIds: ${env:VPC_SUBNET_IDS}
    environment:
        MYSQL_HOST: ${env:MYSQL_HOST, ''}
        MYSQL_PORT: ${env:MYSQL_PORT, ''}
        MYSQL_USER: ${env:MYSQL_USER, ''}
        MYSQL_PASSWORD: ${env:MYSQL_PASSWORD, ''}
        MYSQL_DATABASE: ${env:MYSQL_DATABASE, ''}
        GATEWAYAPI_URL: ${env:GATEWAYAPI_URL, 'http://localhost:8001'}
        GATEWAYAPI_MOCK_ENABLED: ${env:GATEWAYAPI_MOCK_ENABLED, 'true'}
package:
    individually: true

functions:
    ping:
        handler: src/api/ping.handler
        events:
            - http:
                  path: ping
                  method: get
                  cors: true

    saveRegistration:
        handler: src/api/save-registration.handler
        events:
            - http:
                  path: registrations
                  method: post
                  cors: true

    signUp:
        handler: src/api/sign-up.handler
        events:
            - http:
                  path: sign-ups
                  method: post

    deleteAccount:
        handler: src/api/delete-account.handler
        events:
            - http:
                  path: accounts
                  method: delete
                  cors: true

    createAccount:
        handler: src/api/create-account.handler
        events:
            - http:
                  path: accounts
                  method: post
                  cors: true

    updateAccount:
        handler: src/api/update-account.handler
        events:
            - http:
                  path: accounts
                  method: put
                  cors: true

    getAccountById:
        handler: src/api/get-account-by-id.handler
        events:
            - http:
                  path: accounts
                  method: get
                  cors: true

    sendPasswordReminder:
        handler: src/api/send-password-reminder.handler
        events:
            - http:
                  path: password-reminders
                  method: post
                  cors: true

    signOut:
        handler: src/api/delete-session.handler
        events:
            - http:
                  path: sessions
                  method: delete
                  cors: true

custom:

    serverless-offline:
        port: 3001

    pseudoParameters:
        allowReferences: true